# Setup
title: vz
tagline: "the lazy"
description: "under construction.."
url: "https://vz4repo.github.io"
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Hr
  url: http://weclist.com
  email: hrkwon82@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 0.0.2
google_analytics_id: #UA-XXXX-Y
repo: "https://github.com/vz4repo/"
